set(LWIP ${SDK}/Src/Network/lwip2.0.3)

add_library(wmlwip STATIC
    ${SDK}/Src/Network/api2.0.3/tls_sockets.c
    ${SDK}/Src/Network/api2.0.3/tls_netconn.c
    ${LWIP}/core/dns.c
    ${LWIP}/core/def.c
    ${LWIP}/core/init.c
    ${LWIP}/core/mem.c
    ${LWIP}/core/memp.c
    ${LWIP}/core/netif.c
    ${LWIP}/core/pbuf.c
    ${LWIP}/core/raw.c
    ${LWIP}/core/stats.c
    ${LWIP}/core/sys.c
    ${LWIP}/core/tcp.c
    ${LWIP}/core/tcp_in.c
    ${LWIP}/core/tcp_out.c
    ${LWIP}/core/udp.c
    ${LWIP}/core/inet_chksum.c
    ${LWIP}/core/ip.c
    ${LWIP}/core/timeouts.c
    ${LWIP}/core/alg.c
    ${LWIP}/core/ipv4/ip4_frag.c
    ${LWIP}/core/ipv4/ip4_addr.c
    ${LWIP}/core/ipv4/ip4.c
    ${LWIP}/core/ipv4/dhcp.c
    ${LWIP}/core/ipv4/etharp.c
    ${LWIP}/core/ipv4/igmp.c
    ${LWIP}/core/ipv4/icmp.c
    ${LWIP}/core/ipv4/autoip.c
    ${LWIP}/core/ipv6/ip6_frag.c
    ${LWIP}/core/ipv6/ip6_addr.c
    ${LWIP}/core/ipv6/ip6.c
    ${LWIP}/core/ipv6/dhcp6.c
    ${LWIP}/core/ipv6/ethip6.c
    ${LWIP}/core/ipv6/icmp6.c
    ${LWIP}/core/ipv6/inet6.c
    ${LWIP}/core/ipv6/mld6.c
    ${LWIP}/core/ipv6/nd6.c
    ${LWIP}/sys_arch.c
    ${LWIP}/netif/ethernetif.c
    ${LWIP}/netif/ethernet.c
    ${LWIP}/netif/wm_ethernet.c
    ${LWIP}/api/tcpip.c
    ${LWIP}/api/api_lib.c
    ${LWIP}/api/api_msg.c
    ${LWIP}/api/err.c
    ${LWIP}/api/netbuf.c
    ${LWIP}/api/netdb.c
    ${LWIP}/api/netifapi.c
    ${LWIP}/api/sockets.c
)

target_include_directories(wmlwip
    PUBLIC
        ${LWIP}/include
        ${SDK}/Src/Network/api2.0.3
    PRIVATE
        ${SDK}/Include/
        ${SDK}/Include/OS
        ${SDK}/Include/Platform
        ${SDK}/Include/Net
        ${SDK}/Include/App
        ${SDK}/Include/WiFi
        ${SDK}/Platform/inc
        ${SDK}/Platform/Boot/gcc
)